# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :exportLocalizations do
    import_repository(
      url: 'https://github.com/cliqz-oss/ios-l10n-scripts.git',
      clone_folder: "../build-tools",
    )
    sh("cd .. && sh ../build-tools/export-locales-cliqz.sh Client.xcodeproj browser-ios-l10n cliqz-ios.xliff")
  end
  
  lane :importLocalizations do
    #Remove old localization files 
    sh ("rm -rf ../../build-tools ../import-locales-env ../Client/*.lproj")

    # Import Firefox localizations
    import_repository(
      url: 'https://github.com/cliqz-oss/ios-l10n-scripts.git',
      clone_folder: "../build-tools",
    )

    sh("cd .. && sh ../build-tools/import-locales-firefox.sh --release")

    # revert changes that Firefox did to InfoPlist.strings
    sh("cd .. && git checkout Client/en.lproj/InfoPlist.strings")
    sh("cd .. && git checkout Client/en.lproj/Cliqz.strings")


    # Import Cliqz localizations
    import_repository(
      url: 'https://github.com/cliqz-oss/browser-ios-l10n.git',
      clone_folder: "../build-tools/cliqzios-l10n",
    )

    import_cliqz_localizations(
      l10n_folder: "../build-tools/cliqzios-l10n",
      app_name: ENV["app_name"]
    )

  end
  
  lane :clearCache do

    # Remove the Cache
    sh("cd .. && npm cache clean --force && rm -rf Cartfile.resolved Carthage node_modules Pods && rm -rf ~/Library/Caches/org.carthage.CarthageKit")

  end

  lane :prepare do

    # Run Bootstrap for Carthage
    sh("cd .. && carthage bootstrap --verbose --platform ios --color auto --cache-builds")

    # Install NPM and POD Dependencies and Run the Build Script for NPM Dependencies.
    begin
      sh("cd .. && npm install")
    rescue
      sh("cd .. && npm install")
    end
    sh("cd .. && pod install --repo-update")
    sh("cd .. && npm run build")

  end

  lane :nightly do

    # Configuring Sentry DSN
    sh("cd .. && plutil -replace SentryDSN -string $SentryDSN Client/Info.plist")

    # Building ReactNative Entension
    sh("cd .. && npm run bundle-ghostery")

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "new-browser-ios-beta",
      app_identifier: ["com.cliqz.ios.newCliqz", "com.cliqz.ios.newCliqz.ShareTo", "*"],
      readonly: true,
      verbose: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Client.xcodeproj"
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Firefox",
      xcconfig: "Client/Configuration/Firefox.xcconfig",
      xcargs: "OTHER_SWIFT_FLAGS\='$(value) -DBETA'",
      skip_profile_detection: "true",
      export_options: {
        provisioningProfiles: {
          "com.cliqz.ios.newCliqz" => "match AppStore com.cliqz.ios.newCliqz",
          "com.cliqz.ios.newCliqz.ShareTo" => "match AppStore com.cliqz.ios.newCliqz.ShareTo",
        }
      }
    )

    upload_to_testflight(
      changelog: "New Cliqz Nightly build",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'new-cliqz',
    )
  end

  lane :beta do

    # Configuring Sentry DSN
    sh("cd .. && plutil -replace SentryDSN -string $SentryDSN Client/Info.plist")

    # Building ReactNative Entension
    sh("cd .. && npm run bundle-ghostery")

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "ghostery-ios",
      team_id: ENV["DEVELOPER_TEAM_ID"],
      app_identifier: ["com.evidon.Ghostery", "com.evidon.Ghostery.ShareTo", "*"],
      readonly: true,
      verbose: true
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Ghostery",
      xcconfig: "Client/Configuration/Ghostery.xcconfig",
      xcargs: "OTHER_SWIFT_FLAGS\='$(value) -DBETA'",
      skip_profile_detection: "true",
      export_options: {
        provisioningProfiles: { 
          "com.evidon.Ghostery" => "match AppStore com.evidon.Ghostery",
          "com.evidon.Ghostery.ShareTo" => "match AppStore com.evidon.Ghostery.ShareTo",
        }
      }
    )

    upload_to_testflight(
      changelog: "Ghostery Beta",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'ghostery-ios',
    )
  end

  lane :release do

    # Configuring Sentry DSN
    sh("cd .. && plutil -replace SentryDSN -string $SentryDSN Client/Info.plist")

    # Building ReactNative Entension
    sh("cd .. && npm run bundle-ghostery")

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "ghostery-ios",
      team_id: ENV["DEVELOPER_TEAM_ID"],
      app_identifier: ["com.evidon.Ghostery", "com.evidon.Ghostery.ShareTo", "*"],
      readonly: true,
      verbose: true
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Ghostery",
      xcconfig: "Client/Configuration/Ghostery.xcconfig",
      xcargs: "OTHER_SWIFT_FLAGS\='$(value) -DRELEASE'",
      skip_profile_detection: "true",
      export_options: {
        provisioningProfiles: { 
          "com.evidon.Ghostery" => "match AppStore com.evidon.Ghostery",
          "com.evidon.Ghostery.ShareTo" => "match AppStore com.evidon.Ghostery.ShareTo",
        }
      }
    )

    upload_to_testflight(
      changelog: "Ghostery Release",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'ghostery-ios',
    )
  end

  lane :lumenBeta do

    # Configuring Sentry DSN
    sh("sed -i '' 's|sentryDSN:\ String?\ =\ nil|sentryDSN:\ String?\ =\ \"'$SentryDSN'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Configuring Revenuecat APIs
    sh("sed -i '' 's|revenuecatAPI:\ String?\ =\ nil|revenuecatAPI:\ String?\ =\ \"'$RevenuecatAPIKey'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Configuring Lumen APIs
    sh("sed -i '' 's|lumenAPI:\ String?\ =\ nil|lumenAPI:\ String?\ =\ \"'$LumenAPIKey'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Configure CommitHash
    sh("cd .. && plutil -replace CommitHash -string $CommitHash Client/Info.plist")

    # Building ReactNative Entension
    sh("cd .. && npm run bundle-lumen")

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "cliqzPaid-ios",
      team_id: ENV["DEVELOPER_TEAM_ID"],
      app_identifier: ["com.cliqz.ios.cliqzPaid", "com.cliqz.ios.cliqzPaid.ShareTo", "*"],
      readonly: true,
      verbose: true
    )

    version = get_version_number(
      xcodeproj: "Client.xcodeproj", 
      target: "Client"
    )

    increment_build_number(
      build_number: latest_testflight_build_number(version: version) + 1,
      xcodeproj: "Client.xcodeproj"
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Paid",
      xcconfig: "Client/Configuration/Paid.xcconfig",
      xcargs: "OTHER_SWIFT_FLAGS\='$(value) -DBETA'",
      skip_profile_detection: "true",
      export_options: {
        provisioningProfiles: { 
          "com.cliqz.ios.cliqzPaid" => "match AppStore com.cliqz.ios.cliqzPaid",
          "com.cliqz.ios.cliqzPaid.ShareTo" => "match AppStore com.cliqz.ios.cliqzPaid.ShareTo",
        }
      }
    )

    upload_to_testflight(
      changelog: "CliqzPaid Beta",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'lumen-staging-ios',
    )
  end

  lane :lumenRelease do

    # Configuring Sentry DSN
    sh("sed -i '' 's|sentryDSN:\ String?\ =\ nil|sentryDSN:\ String?\ =\ \"'$SentryDSN'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Configuring Revenuecat APIs
    sh("sed -i '' 's|revenuecatAPI:\ String?\ =\ nil|revenuecatAPI:\ String?\ =\ \"'$RevenuecatAPIKey'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Configuring Lumen APIs
    sh("sed -i '' 's|lumenAPI:\ String?\ =\ nil|lumenAPI:\ String?\ =\ \"'$LumenAPIKey'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Configure CommitHash
    sh("cd .. && plutil -replace CommitHash -string $CommitHash Client/Info.plist")

    # Building ReactNative Entension
    sh("cd .. && npm run bundle-lumen")

    create_keychain(
      path: "/Users/vagrant/Library/Keychains/"+ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "lumen-ios",
      team_id: ENV["DEVELOPER_TEAM_ID"],
      app_identifier: ["com.cliqz.ios.lumen", "com.cliqz.ios.lumen.ShareTo", "*"],
      readonly: true,
      verbose: true
    )

    version = get_version_number(
      xcodeproj: "Client.xcodeproj", 
      target: "Client"
    )
    
    increment_build_number(
      build_number: latest_testflight_build_number(version: version) + 1,
      xcodeproj: "Client.xcodeproj"
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Lumen",
      xcconfig: "Client/Configuration/Lumen.xcconfig",
      xcargs: "OTHER_SWIFT_FLAGS\='$(value) -DRELEASE'",
      skip_profile_detection: "true",
      export_options: {
        provisioningProfiles: { 
          "com.cliqz.ios.lumen" => "match AppStore com.cliqz.ios.lumen",
          "com.cliqz.ios.lumen.ShareTo" => "match AppStore com.cliqz.ios.lumen.ShareTo",
        }
      }
    )

    upload_to_testflight(
      changelog: "Lumen Browser",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'lumen-ios',
    )
  end

  lane :cliqzNightly do

    # Configuring Sentry DSN
    sh("sed -i '' 's|sentryDSN:\ String?\ =\ nil|sentryDSN:\ String?\ =\ \"'$SentryDSN'\"|' ../Cliqz/Resources/APIKeys.swift")

    # Building ReactNative Extension
    sh("cd .. && npm run bundle-cliqz")

    create_keychain(
      path: "/Users/vagrant/Library/Keychains/"+ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "browser-ios",
      app_identifier: ["com.cliqz", "com.cliqz.ShareTo"],
      readonly: true,
      verbose: true
    )

    increment_version_number(
      version_number:"2.0.0", 
      xcodeproj:"Client.xcodeproj"
    )

    version = get_version_number(
      xcodeproj: "Client.xcodeproj", 
      target: "Client"
    )

    increment_build_number(
      build_number: latest_testflight_build_number(version: version) + 1,
      xcodeproj: "Client.xcodeproj"
    )

    build_app(
      workspace: "Client.xcworkspace",
      clean: "true",
      scheme: "Cliqz",
      xcconfig: "Client/Configuration/Cliqz.xcconfig",
      xcargs: "OTHER_SWIFT_FLAGS\='$(value) -DRELEASE'",
      skip_profile_detection: "true",
      export_options: {
        provisioningProfiles: {
          "com.cliqz" => "CLIQZ App Store",
          "com.cliqz.ShareTo" => "CliqzShareTo Distribution",
        }
      }
    )

    upload_to_testflight(
      changelog: "Cliqz Nightly build",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true"
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'cliqz-ios',
    )
  end
end
